cloudflare/cloudflare-ingress-controller

README.md
I tried this yesterday and found that the instructions had to be adjusted slightly.
One of the YAML file names was incorrect, and the namespace has to be passed
as a command line argument to the controller when deploying it.
I also added a few steps to clarify what's required (for somebody who
has never used warp and perhaps never used cloudflare either).
If you don't like the way I rephrased the instructions, feel free to drop this PR
and incorporate just the changes that you like :-)
=> Fix file name and add a few details

chart/.helmignore, chart/Chart.yaml, chart/README.md, chart/templates/NOTES.txt, chart/templates/_helpers.tpl, chart/templates/deployment.yaml, chart/templates/rbac-role.yaml, chart/templates/rbac-rolebinding.yaml, chart/templates/secret.yaml, chart/templates/serviceaccount.yaml, chart/values.yaml
fixes https://github.com/cloudflare/cloudflare-warp-ingress/issues/7
helm chart was taken from: https://github.com/dcos-labs/charts/tree/master/stable/cloudflare-warp-ingress
=> added helm chart

chart/Chart.yaml, chart/templates/rbac-clusterrole.yaml, chart/values.yaml, deploy/nginx.yaml, pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/tunnel/tunnel.go
Refactoring ingress handling to support all updates of ingresses and set ingress status fields,
=> support for updating ingress and setting ingress status

Gopkg.lock, Gopkg.toml, Makefile, README.md, build/build.sh, chart/Chart.yaml, chart/README.md, chart/templates/NOTES.txt, chart/templates/deployment.yaml, chart/templates/rbac-role.yaml, chart/templates/rbac-rolebinding.yaml, chart/templates/secret.yaml, chart/values.yaml, cmd/argot/flags.go, cmd/argot/main.go, deploy/cloudflare-argo-role.yaml, deploy/cloudflare-argo-rolebinding.yaml, pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/tunnel/argo.go
updates dependencies, uses go 1.10
customizes the httpClient
allows specifying a custom ingress class name
changes secret lookup to use the domain label
updates helm resources
=> Httpclient, secrets, ingress classes

pkg/controller/const.go, pkg/controller/controller.go
Closes #41 
Master did not compile.  Running git bisect makes this appear to be a good candidate to resolve. Tests pass with this commit.
=> Fix compile errors, adding consts back

README.md
=> Update link reference to code-of-conduct

Dockerfile, hack/Dockerfile
=> Update dockerfile copy paths

Dockerfile, hack/Dockerfile
=> Allow build to stamp version from makefile

Gopkg.lock, cmd/argot/main.go, internal/controller/controller.go
The signal handler and controller are broken into separate run groups
which be be leveraged by future additions (specifically separate metric
and debug handlers)
=> group signal handler and controller

internal/tunnel/argo.go
A panic has been observed in cloudflared, caused by closing an already
closed channel (the connectedSignal channel). A panic will terminate the
entire controller (impacting all active tunnels).  This change traps the
panic and converts it into an error sent down errCh, triggering the
tunnel repair mechanism (rebuilding the tunnel rather than killing the
controller).
relates to #40
=> trap and recover from origin panics

internal/tunnel/argo.go
To by-pass issues where a tunnel was left in a bad state and is not
properly deregistered, regenerate the client id as part of the repair
flow. Issue #40 directly reports this state, where the tunnel died
during connect. The internal (part of cloudflared) retry mechanism
failed and terminated the controller tunnel instance.  A retry with the
same ClientID would continue to produce the same failure until the
original tunnel was deregistered cleanly; renegerating the ClientID
allows for faster recovery.
=> regenerate the client id during repair

internal/argotunnel/informer.go, internal/argotunnel/informer_test.go
Indexes are used to maintain relationshipd between object (the graph of
objects).  Only index ingress objects containing matching ingress.class
to avoid attempting to maning ingress objects that don't match class.
closes #124
=> Only index ingress objects matching ingress.class

internal/argotunnel/translator.go
=> allow "/" to be treated as empty path

Makefile
=> issue-140: add 32bit arm support

cmd/argot/main.go, internal/argotunnel/tunnel.go, internal/argotunnel/tunnel_test.go, internal/argotunnel/version_test.go
=> expands cmd flags to configure tunnel defaults

Gopkg.lock, Gopkg.toml, cmd/argot/main.go, docs/controls.md, internal/argotunnel/transportlogger.go, internal/argotunnel/tunnel.go
=> chore: update to cloudflared 2019.1.0

Dockerfile, hack/Dockerfile
=> chore: update golang to 1.10.8

Dockerfile, hack/Dockerfile
=> chore: upgrade to alpine 3.9.0

internal/argotunnel/tunnel.go
=> reset config runtime state during repair

deploy/argo-tunnel-no-rbac.yaml, deploy/argo-tunnel.yaml
Update the image of argo-tunnel on the deployments.
=> Update deployments to latest argo-tunnel
