cloudflare/cloudflare-ingress-controller

deploy/warp-controller-deployment.yaml

This upgrade fix the bug reported here: https://github.com/cloudflare/cloudflare-warp-ingress/issues/2
Docker Container Version syntax was changed.

Update to new container release v0.3.1

---

README.md

Fix typo (fancfy)
Add explicit reference to `-namespace` flag in `command` block
Add example `kubectl create --namespace` command

Improve README namespace documentation

---

Gopkg.lock
Gopkg.toml
pkg/controller/controller.go
pkg/controller/controller_test.go
pkg/tunnel/metrics.go
pkg/tunnel/tunnel.go
pkg/tunnel/warp.go
pkg/tunnel/warp_test.go

Support multiple namespace with one ingress controller. The secret containing the cloudflared token+certificate must be in the same namespace as the controller.
Updates the library dependency to cloudflare/cloudflared:2018.4.0 with *the important warning* that it does not compile out-of-the-the box against that library.  Instead, the library must make origin.tunnelMetrics public again.

multiple namespaces

---

Makefile
README.md
chart/.helmignore
chart/Chart.yaml
chart/README.md
chart/templates/NOTES.txt
chart/templates/_helpers.tpl
chart/templates/clusterrole.yaml
chart/templates/clusterrolebinding.yaml
chart/templates/deployment.yaml
chart/templates/role.yaml
chart/templates/rolebinding.yaml
chart/templates/serviceaccount.yaml
chart/values.yaml
deploy/argo-tunnel-no-rbac.yaml

This restores the helm chart deleted with #45 and updates the
documentation for the chart to provide configuration details. It does
not restore secret installation from the helm chart.
fixes #7

Restore the helm chart

---

chart/templates/deployment.yaml

Fixes the error
```
Error: YAML parse error on argo-tunnel/templates/deployment.yaml: error converting YAML to JSON: yaml: line 21: did not find expected key
```

Correct YAML indenting

---

Dockerfile
hack/Dockerfile

Add -extldflags -static to -ldflags and -tags netgo to build command to
increase likelyhood of a fully static binary.
fixes #56

Add -extldflags -static and -tags netgo

---

internal/controller/annotations.go
internal/controller/annotations_test.go
internal/controller/const.go
internal/controller/controller.go
internal/controller/controller_test.go

Move the annotations into a separate file with names that suggest they
are annotations.  This will help us quantify and expand annotation
support in the future.  Parsing functions are added that generically
consume objsand convert them to meta object accessors.  This object
conversion may be unnessecary; however, parsing the annotation for
ingress class was not consistent with the load balancer pool (object
sections obj.Annotations vs obj.ObjectMeta.Annotations respectively).

Separate annotations and provide consistent parsing

---

cmd/argot/main.go
internal/controller/const.go
internal/controller/controller.go
internal/controller/controller_test.go
internal/controller/options.go
internal/controller/options_test.go

Remove the config struct and replace it with an option pattern.  This
allows configuration to be both less exposed (doesn't need to be
exported) and partial (only provide the options that are changing,
rather than the entire struct).  The base mechanism will be expanded,
allowing greater control (from either flags or annotations).

Replace config struct  with option pattern

---

Gopkg.lock
Makefile
internal/controller/controller.go
internal/controller/controller_test.go
internal/tunnel/argo.go
internal/tunnel/registry.go
internal/tunnel/registry_test.go
internal/tunnel/tunnel_test.go

The change targets resolving thread-safety issues in source.  It does
not resolve thread-safety issues detected in the test code, though the
explicit sleeps have been replaced with more resilient mechanisms
- tests will wait for caches to sync after running the controller
- tests will poll for changes at 100ms intervals, timing out at 10s
Enabling race dection as part of the PR checks is not ready. The test
code with race issues will be resolved with the reformer refactor.
Any other error/issues discovered in shared code paths have been
preserved and marked for future fix.
fixes #68

Resolves thread-safety issues on tunnel shutdown

---

internal/tunnel/argo.go
internal/tunnel/argo_test.go

Cloudflared uses a default of 4 ha connections, the controller should do
the same.

Set default ha connections to 4

---

chart/templates/deployment.yaml
chart/values.yaml

The original helm chart did offer resource controlls, this adds those
controls back to the helm chart.  Be advised, the cpu and memory limits
have not been vetted and should not be assumed to be suggested values.

re-add resource controls for helm chart

---

Makefile
docs/controls.md
internal/controller/annotations.go
internal/controller/annotations_test.go
internal/controller/controller.go
internal/controller/controller_test.go
internal/tunnel/argo.go
internal/tunnel/argo_test.go
internal/tunnel/options.go
internal/tunnel/options_test.go
internal/tunnel/registry_test.go
internal/tunnel/route.go
internal/tunnel/tunnel.go
internal/tunnel/tunnel_test.go

The change expands the set of annotations allow as part of the ingress
definition, allowing control similar to `cloudflared` command-line
flags. This expansion does not offer http transport configuration (e.g.
adjustment to proxy settings).

expand annotations to allow tunnel configuration

---

cmd/argot/main.go
cmd/argot/main_test.go
internal/controller/controller.go
internal/controller/controller_test.go
internal/tunnel/argo.go
internal/tunnel/argo_test.go
internal/tunnel/tunnel.go
internal/tunnel/tunnel_test.go

Previously, the code base leveraged both loggers, glog and logrus, in
different portions of the code.  THis change consolidates loggers to one
variant, logrus.  The kubernentes client internally uses glog, which
defines the --v flag.  To avoid altering the optiosn for 0.5.x, the
mechanism is preserved.  The value for --v is mapped into a logrus level
and set to the shared logger.

replace glog with logrus

---

Gopkg.lock
cmd/argot/main.go
cmd/argot/main_test.go
deploy/argo-tunnel-no-rbac.yaml
deploy/argo-tunnel.yaml
internal/controller/options.go
internal/k8s/types.go
internal/k8s/types_test.go

BREAKING CHANGE from 0.5.x. Migrates flags to command-style cli with 2
commands, version and couple. The change includes removal of the flag
`-namespace`, preferring an alternate to secret location/control.

convert cmd-line flags to cli

---

internal/argotunnel/translator.go
internal/argotunnel/translator_test.go
internal/argotunnel/tunnel.go
internal/argotunnel/tunnel_test.go

The certificate should be checked for the host prior to launching a
tunnel; otherwise, starting the tunnel will trigger the repair loop.

verify certificate for host prior to starting tunnel

---

internal/argotunnel/translator.go
internal/argotunnel/translator_test.go
internal/k8s/audit.go
internal/k8s/audit_test.go

As part of ingress validation prior to starting a tunnel, verify that
the service parget port matches an endpoint port (otherwise the tunnel
will launch but be of no value)

verify service target port matches an endpoint port

---

deploy/argo-tunnel-no-rbac.yaml
deploy/argo-tunnel.yaml
docs/controls.md
docs/guide_first_tunnel.md
docs/guide_ha_tunnel.md
docs/guide_subdomain_tunnel.md

The refresh largely removes caveats sections as the updated resource
handling for 0.6.x removes restrictions of both ingresses and secrets.

refreshing docs for 0.6.x

---

Dockerfile
hack/Dockerfile

Migrate to 1.10.6 to resolve security issue with crypto/x509, cpu
denial of service in chain validation. The issue is CVE-2018-16875
and Go issue golang.org/issue/29233

upgrade to go 1.10.6 to resolve security issue

---

cmd/argot/main.go
docs/controls.md
docs/guide_origin_secret_config.md
internal/argotunnel/informer.go
internal/argotunnel/informer_test.go
internal/argotunnel/options.go
internal/argotunnel/options_test.go
internal/argotunnel/translator.go
internal/cloudflare/originsecret.go
internal/cloudflare/originsecret_test.go

Adds the command-line flag `--origin-secret-config`, allowing
specification of a host specific default secret mapping file.  The
additional configuration is meant to help with migration from 0.5.x to
0.6.x and allows isolation of reuseable secrets.
Resolves #126

adds origin-secret-config mapping file

---

internal/argotunnel/translator.go
internal/argotunnel/translator_test.go
internal/k8s/audit.go
internal/k8s/audit_test.go

It is sufficient to verify existience of ready addresses without
attempting to match ports.
resolves #139

issues-139: incorrect server to subset port match

---

cmd/argot/main.go
docs/controls.md
internal/argotunnel/protologger.go
internal/argotunnel/tunnel.go

Adds flag `proto-log-enable`.  When enabled, the protocol logger will be
given the same log-level as the controller logger.
resolves #145

issue-145: allow protocol logging to be enabled
